#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mError\033[1;33m] \033[1;37m- \033[1;33mAnda harus login sebagai root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
cd $HOME
echo "Update & Install Aplikasi Pendukung..."
sleep 2s
echo ""
apt update -y; apt upgrade -y; apt install wget curl

#Loading animasi----------------------------------------
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33mHOLD \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<25; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33mHOLD \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}

#Validasi Key---------------------------------------------
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
  echo -e "\n\033[1;31mINVALID KEY!\033[0m"
  rm -rf $HOME/Plus > /dev/null 2>&1
  sleep 2
  clear; exit 1
}
}

#Header----------------------------------------------------
clear
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;32m               ROCKNETSSH MANAGER                   \033[0m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;33mAUTOSCRIPT INI DI EDIT KEMBALI OLEH ADMIN ROCKNETVPN\033[0m"
echo -e "\033[1;33m MASIH DALAM PENGEMBANGAN UNTUK HASIL YANG SEMPURNA \033[0m"
echo -e "\033[1;33m   ANDA DAPAT MEMBUAT USER AKUN LEWAT BOT TELEGRAM  \033[0m"
echo -e "\033[1;33m     DAN MEMANAGEMENT AKUN DENGAN SANGAT MUDAH!     \033[0m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e "\033[1;32m   INFO LEBIH LANJUT HUB. TELEGRAM: @RocknetStore   \033[0m"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"

#-----------------------------------------------------------------------------------------------------------------
read -p "$(echo -e "\033[1;36mAPAKAH INGIN MELANJUTKAN ? \033[1;33m[y/N]:\033[0m")" -e -i y resp
[[ $resp = @(n|N) ]] && rm $HOME/Plus && exit 0
cp /etc/ssh/sshd_config /etc/ssh/sshd_back
wget -O /etc/ssh/sshd_config https://raw.githubusercontent.com/rockneters/jalingkut/main/Install/sshd_config > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\033[1;36mChecking Permission....\033[0m" 
#verif_key
sleep 3s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
echo "apt-get update -y; apt-get upgrade -y; wget https://raw.githubusercontent.com/rockneters/jalingkut/main/Plus; chmod 777 Plus; ./Plus" > /bin/sshplus; chmod +x /bin/sshplus > /dev/null 2>&1
wget -O /bin/menu https://raw.githubusercontent.com/rockneters/jalingkut/main/Modulos/menu > /dev/null 2>&1; chmod +x /bin/menu
clear

#Database------------------------------------------------------------------------
echo -e "\033[1;36mChecking Database....\033[0m"
sleep 3s
[[ -f "$HOME/usuarios.db" ]] && {
    echo -e "\033[0;34m========================================================\033[0m"
    echo -e "\033[1;33mDatabase user telah ditemukan !!\033[0m"
    echo -e "\033[1;33mApakah akan menggunakan Database lama atau membuat baru?\033[0m" 
	echo -e "\033[1;37m[1] \033[1;33mMenggunakan Database lama\033[0m"
	echo -e "\033[1;37m[2] \033[1;33mMembuat Database baru\033[0m"
	echo -e "\033[0;34m========================================================\033[0m"
    echo ""
	read -p "Option?: " -e -i 1 optiondb
} || {
	awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear

#Installing------------------------------------------------------------------------
echo -e "\033[0;34m========================================================\033[0m"
echo -e "\033[1;33m|                WAIT FOR INSTALLATION                 |\033[0m"
echo -e "\033[0;34m========================================================\033[0m"
echo ""
echo -e "\033[1;33m[!] \033[1;32mUPDATING SYSTEM \033[1;33m[!]\033[0m"
echo ""
echo -e "\033[1;33mMEMBUTUHKAN WAKTU BEBERAPA MENIT!\033[0m"
fun_attlist () {
    apt-get update -y
	[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
	echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'

echo ""
echo -e "\033[1;33m[!] \033[1;32mINSTALL PACKAGE \033[1;33m[!]\033[0m"
echo -e "\033[1;33mMEMBUTUHKAN WAKTU LEBIH LAMA!\033[0m"
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "figlet" "python3" "python-pip" "ufw")
for _prog in ${_pacotes[@]}; do
    apt install $_prog -y
done
ufw enable
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/etc/default/ufw" ]] && ufw allow 443/tcp; ufw allow 80/tcp; ufw allow 3128/tcp; ufw allow 8799/tcp; ufw allow 8080/tcp; ufw allow 7100:7300/tcp

echo ""
echo -e "\033[1;33m[!] \033[1;32mFINISHING \033[1;33m[!]\033[0m"
echo -e "\033[1;33mCOMPLETING FUNCTIONS AND SETTINGS! \033[0m"
echo ""
#fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
echo ""
cd $HOME
echo -e "\033[1;33m • \033[1;32mINSTALLATION COMPLETED\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mMAIN COMMAND: \033[1;32mmenu\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
clear
wget -N --no-check-certificate -q -O install.sh "https://raw.githubusercontent.com/rockneters/piturays/master/install.sh" && chmod +x install.sh && bash install.sh
